name: Continuous Deployment

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: /var/www/urban

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          path: dreamcubeid-urban-${{ github.run_id }}-${{ github.run_number }}
      
      - run: | 
          rsync -a dreamcubeid-urban-${{ github.run_id }}-${{ github.run_number }}/ /var/www/urban/
          rm -rf dreamcubeid-urban-${{ github.run_id }}-${{ github.run_number }}
        working-directory: /home/urban/actions-runner/_work/urban/urban

      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build

      - name: Install production only dependencies
        run: npm ci --only=production
      
      - name: Restart server application
        run: pm2 restart urban