name: Continuous Integration

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  merge_pull_request:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
      
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      
      - name: Install dependencies
        run: npm install

      - name: Build application
        run: npm run build
